// Provide Anchor API for certain usage

#let _anchor-series = state("_anchor-series", (:))

/// Create an anchor with specified prefix and number. `prefix` should be a non-empty string, and `nums` should be an array of integers.
/// - prefix (str): The prefix of the anchor ID, should be a non-empty string.
/// - ..nums (int): The number sequence to generate the anchor ID, should be an array of integers. The final anchor ID will be generated by concatenating the prefix and the number sequence with hyphens, e.g. `prefix-1-2-3` for prefix "prefix" and nums [1, 2, 3].
/// -> str
#let create(prefix, ..nums) = {
  assert(type(prefix) == str and prefix.len() > 0, message: "prefix must be a non-empty string")
  let id = prefix
  for num in nums.pos() {
    assert(type(num) == int, message: "members of nums must be integers")
    id += "-" + str(num)
  }
  assert(not _anchor-series.get().keys().contains(id), message: "Anchor ID '" + id + "' already exists")
  _anchor-series.update(dic => if dic == none { (id: none) } else {
    dic.insert(id, none)
    dic
  })
  metadata(id)
}

/// Find specified anchor. Can be used in to ways, either by providing the full anchor ID, or by providing the prefix and number sequence to generate the anchor ID.
/// - prefix (str): The prefix of the anchor ID, should be a non-empty string or none by default.
/// - id (str | none): The full anchor ID, should be a non-empty string. If provided, it will be used directly, and `prefix` and `nums` will be ignored.
/// - ..nums (int): The number sequence to generate the anchor ID, should be an array of integers. Will be ignored
/// -> metadata | none
#let find(prefix, id: none, ..nums) = {
  // targeted lookup anchor id
  let target = none
  if id != none {
    assert(type(id) == str and id.len() > 0, message: "id must be a non-empty string")
    target = id
  } else {
    target = prefix
    for num in nums.pos() {
      assert(type(num) == int, message: "members of nums must be integers")
      target += "-" + str(num)
    }
  }
  let result = query(metadata.where(value: target))
  if result.len() == 0 {
    none
  } else if result.len() == 1 {
    result.at(0)
  } else {
    panic("multiple metadata entries have the same Anchor ID '" + target + "'，please check your code to ensure each Anchor ID is unique")
  }
}

/// Find specified anchor location. Can be used in to ways, either by providing the full anchor ID, or by providing the prefix and number sequence to generate the anchor ID.
/// - prefix (str): The prefix of the anchor ID, should be a non-empty string or none by default.
/// - id (str | none): The full anchor ID, should be a non-empty string. If provided, it will be used directly, and `prefix` and `nums` will be ignored.
/// - ..nums (int): The number sequence to generate the anchor ID, should be an array of integers. Will be ignored
/// -> dictionary | none
#let findpos(prefix, id: none, ..nums) = {
  // targeted lookup anchor id
  let target = none
  if id != none {
    assert(type(id) == str and id.len() > 0, message: "id must be a non-empty string")
    target = id
  } else {
    target = prefix
    for num in nums.pos() {
      assert(type(num) == int, message: "members of nums must be integers")
      target += "-" + str(num)
    }
  }
  let result = query(metadata.where(value: target))
  if result.len() == 0 {
    none
  } else if result.len() == 1 {
    result.at(0).location().position()
  } else {
    panic("multiple metadata entries have the same Anchor ID '" + target + "'，please check your code to ensure each Anchor ID is unique")
  }
}

/// A helper function provide fast access to the Anchor API with a fixed prefix. `prefix` should be a non-empty string.
/// 
/// Please note that it should be used like:
/// 
/// ```typst
/// let (num-anc-create, _, num-anc-findpos) = anchor-helper("num-anc")
/// // or
/// let num-anc = anchor-helper("num-anc")
/// (num-anc.create)(1, 2, 3)
/// (num-anc.findpos)(1, 2, 3)
/// ```
/// - prefix (str): The prefix of the anchor ID, should be a non-empty string.
/// -> dictionary
#let anchor-helper(prefix) = (
  create: (..nums) => create(prefix, ..nums),
  find: (id, ..nums) => find(prefix, id, ..nums),
  findpos: (id, ..nums) => findpos(prefix, id, ..nums),
)
